export enum ETextureName {
	ROOT           = "assets/spritesheets/spritesheet.json",
	START_BUTTON   = "button.png",
	WALL           = "wall.png",
	SMALL_WALL_1   = "small_wall_1.png",
	SMALL_WALL_2   = "small_wall_2.png",
	SMALL_WALL_3   = "small_wall_3.png",
	SMALL_WALL_4   = "small_wall_4.png",
	PLAYER_TANK    = "tank.png",
	ENEMY_BLUE     = "enemy_blue.png",
	ENEMY_RED      = "enemy_red.png",
	ENEMY_WHITE    = "enemy_white.png",
	GRASS          = "leaves.png",
	EAGLE          = "eagle.png",
	WATER          = "water.png",
	ENEMY_BULLET   = "enemy_bullet.png",
	PLAYER_BULLET  = "bullet.png",
	EXPLODE        = "explode",
	BONUS_IMMORTAL = "bonus_immortal.png",
	BONUS_LIFE     = "bonus_live.png",
	BONUS_SLOW     = "bonus_slow.png",
	BONUS_SPEED    = "bonus_speed.png"
}
